version: "3.9"

services:
  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PORT:-8080}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - front-end
      - listings
      - warehouse
      - orders

  front-end:
    image: ghcr.io/mcmastercce/bvd-103-mcmasterful-books/mcmasterful-books-docker:main
    volumes:
      - ./adapter:/source/adapter

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"  # management UI

  listings:
    build:
      context: ./listings
    working_dir: /app
    command: npx -y tsx index.ts
    volumes:
      - ./listings:/app
    depends_on:
      - mongo
      - rabbitmq
    env_file:
      - .env

  warehouse:
    build:
      context: ./warehouse
    working_dir: /app
    command: npx -y tsx index.ts
    volumes:
      - ./warehouse:/app
    depends_on:
      - mongo
      - rabbitmq
    env_file:
      - .env

  orders:
    build:
      context: ./orders
    working_dir: /app
    command: npx -y tsx index.ts
    volumes:
      - ./orders:/app
    depends_on:
      - mongo
      - rabbitmq
    env_file:
      - .env

volumes:
  mongo_data:
