version: '3.9'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - front-end
      - server1
      - server2
      - server3

  front-end:
    image: ghcr.io/mcmastercce/bvd-103-mcmasterful-books/mcmasterful-books-docker:main
    volumes:
      - ./adapter:/source/adapter

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server1:
    image: node:20
    working_dir: /app
    volumes:
      - ./:/app
    command: npx -y tsx ./index.ts
    depends_on:
      - mongo

  server2:
    image: node:20
    working_dir: /app
    volumes:
      - ./:/app
    command: npx -y tsx ./index.ts
    depends_on:
      - mongo

  server3:
    image: node:20
    working_dir: /app
    volumes:
      - ./:/app
    command: npx -y tsx ./index.ts
    depends_on:
      - mongo

volumes:
  mongo_data:
